# eza_aliases.sh
alias ld='eza -lD'
alias lf='eza -lF --color=always | grep -v /'
alias lh='eza -dl .* --group-directories-first'
alias ll='eza -al --group-directories-first'
alias ls='eza -alF --color=always --sort=size | grep -v /'
alias lt='eza -al --sort=modified'
alias lr='eza -al --sort=modified --reverse'
alias ldir='eza -d */'
alias li='eza -ali'
alias lx='eza -la@'
alias ltree='eza --tree'
