# ~/.config/alacritty/alacritty.toml

# Font configuration
[font]
size = 13.0

[font.normal]
family = "Hack Nerd Font"
style = "Regular"

# Shell configuration (Zsh with automatic tmux session attach)
[shell]
program = "zsh"
args = ["-l", "-c", "tmux attach || tmux"]

# Custom keybindings (emulate Alt + arrow keys for word navigation)
[[keyboard.bindings]]
key = "Right"
mods = "Alt"
chars = "\u001Bf"  # Move cursor forward by word

[[keyboard.bindings]]
key = "Left"
mods = "Alt"
chars = "\u001Bb"  # Move cursor backward by word

# Window configuration (optional, improves visual experience)
[window]
opacity = 0.95          # Slight transparency for improved readability
padding = { x = 8, y = 8 }  # Add padding around the terminal text

# Cursor customization (optional, enhances visibility)
[cursor]
style = { shape = "Block", blinking = "Always" }
blink_interval = 500

# Color scheme (optional, recommended for visual consistency)
[colors.primary]
background = "#1d1f21"
foreground = "#c5c8c6"

[colors.normal]
black   = "#282a2e"
red     = "#a54242"
green   = "#8c9440"
yellow  = "#de935f"
blue    = "#5f819d"
magenta = "#85678f"
cyan    = "#5e8d87"
white   = "#707880"

[colors.bright]
black   = "#373b41"
red     = "#cc6666"
green   = "#b5bd68"
yellow  = "#f0c674"
blue    = "#81a2be"
magenta = "#b294bb"
cyan    = "#8abeb7"
white   = "#c5c8c6"

# ───── Paste strictly with Ctrl+V ────────────────────────────
[[keyboard.bindings]]
key     = "V"
mods    = "Control"
action  = "Paste"

# ───── Disable other paste shortcuts you don’t want ──────────
[[keyboard.bindings]]
key     = "V"
mods    = "Control|Shift"
action  = "None"          # turns off Ctrl+Shift+V

[[keyboard.bindings]]
key     = "Insert"
mods    = "Shift"
action  = "None"          # turns off Shift+Insert (optional but recommended)

# ─── Make Ctrl+Backspace send Ctrl+W (back-delete word) ───────────────
[[keyboard.bindings]]
key     = "Back"
mods    = "Control"
chars   = "\u0017"        # 0x17 = ^W = backward-kill-word in most shells

# (optional) turn off Alt+Backspace if you don’t want it
#[[keyboard.bindings]]
#key   = "Back"
#mods  = "Alt"
#action = "None"
